### ISSUE TITLE
BO - Product details page - an error is displayed in the console

### ISSUE THREAD

**Issue by MatShir** [PrestaShopCorp/ps_mbo#109]
#### Describe the bug

In the BO > Catalog > Products > Products details page > an error is displayed in the console
![image](https://user-images.githubusercontent.com/16067358/113714544-cbc20000-96e8-11eb-84df-e02157d7b711.png)

#### Expected behavior

No error displayed

#### Steps to Reproduce

1. Go to BO > Catalog > Product list page
2. Add/Edit a product

PS1773 => OK

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2
* original issue: https://github.com/PrestaShop/PrestaShop/issues/23899

**Comment by caglarutkuguler** [comment]
Any progress on this issue?

**Comment by intraordinaire** [comment]
No evolution/fixes will be done on 2.x versions

**Comment by intraordinaire** [comment]
I've made a quick & dirty fix for this one.
IMHO, the best way to solve this permanently is to avoid to load duplicate script when we use `addJS` method.

**Comment by intraordinaire** [comment]
It's finally done 🎉
Release 2.0.3 [here](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v2.0.3)
