### ISSUE TITLE
BO - module_card.js is imported two times on the product page v1

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShopCorp/ps_mbo#217]
For reference: https://github.com/PrestaShop/PrestaShop/issues/28047

The bundle `module_card.js` is added [here](https://github.com/PrestaShopCorp/ps_mbo/blob/c3ac864869e4956135fdb805f5dfa35c9680f2df/ps_mbo.php#L320-L329) but it's duplicated on the product page v1

Do we have a way to verify that the `asset` is already registered on the page? 

Can we just remove it from the core? Idk if we have some dependencies related to it, maybe the whole bundle can still be removed!

I need your advice.

**Comment by intraordinaire** [comment]
Hey !

I'm not sure if there is a way to check if an asset is already added to the page, but as I understand, when using the `addJS` method, this check should occur [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/controller/Controller.php#L518).

Unfortunately, in this version of the MBO module, 80% of the code is in the core... A migration has been made, but will be compatible with PS>8 only.
So this file can be removed from the 8.x versions if you don't use it anymore.

Anyway, I think we can still fix this issue either by trying to load the JS only if needed (check what's going wrong in the `addJS` method or by checking in the JS file if the variables already exists, and do nothing if this is the case.

**Comment by intraordinaire** [comment]
This issue is already reported [here](https://github.com/PrestaShopCorp/ps_mbo/issues/109) in this repository too.

**Comment by NeOMakinG** [comment]
I guess as this is a duplicate, we can still close this issue!

I'll probably remove the file from the core if we don't rely on it at all, thanks for your response!
