### ISSUE TITLE
Design issue on payment methods page

### ISSUE THREAD

**Issue by marionf** [PrestaShopCorp/ps_mbo#30]
When MBO is installed, the recommanded modules on the payment methods page are not well displayed and images are not displayed

![capture d ecran_215](https://user-images.githubusercontent.com/13449658/44857921-1ba6d380-ac71-11e8-8be4-02752b9a3122.png)

**Comment by MrBaiame** [comment]
It's on the new prestashop version right ? this one seems to be a symfony controller ?

**Comment by Quetzacoalt91** [comment]
Yes, this is a preview of the Payment methods page, on the next PS release.
