### ISSUE TITLE
Documentation ps_accounts leads 404

### ISSUE THREAD

**Issue by wirthandras** [PrestaShopCorp/ps_mbo#367]
The link in readme [https://github.com/PrestaShopCorp/ps_accounts](https://github.com/PrestaShopCorp/ps_accounts) leads 404

**Comment by intraordinaire** [comment]
Hello @wirthandras 
Indeed, this is because this repository (ps_account) is private.
Also, this one, ps_mbo, will also be private in a couple of days.

Thanks
