### ISSUE TITLE
Design of "Read more" modal

### ISSUE THREAD

**Issue by marionf** [PrestaShopCorp/ps_mbo#42]
The design of "Read more" modal isn't pretty

![capture d ecran_316](https://user-images.githubusercontent.com/13449658/45956081-f4de8180-c011-11e8-9909-01fbc8610167.png)

It is better without MBO :

![capture d ecran_317](https://user-images.githubusercontent.com/13449658/45956085-f90a9f00-c011-11e8-82c3-c8b0fb72336f.png)

**Comment by LouToma** [comment]
Etrange car au test la semaine dernière, le read more était ok.
Qui s'en occupe, @Alexisvallee ?

**Comment by colinegin** [comment]
Vu en sprint planning - à traiter lors d'un lot 2 (après fix des issues bloquantes)

**Comment by LouToma** [comment]
ok
