### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by tajriba** [PrestaShopCorp/ps_mbo#430]
error:
ps_mbo. Employee->email is empty

also it says installed I see no database values for the module and reset the module gives this: Warning: mkdir(): No such file or directory. version 4.3

PS 801 php 8.1

**Comment by intraordinaire** [comment]
Hello @tajriba ,

Thanks for your report.
We will take a look at this.
In the meantime, can you provide us more details, logs, screenshots of these errors please ?

**Comment by sowbiba** [comment]
Hi @tajriba
Thanks for your report
I'll ask some questions to help us understand your issue
Do you have access to the database?
Are you confortable enough to query the DB and see if you have an employee with firstname=Marketplace lastname=Prestashop ? (do not paste the line here, I just to know if the employee exists and has a non-empty email)
Did you do any special thing after installing MBO?

Thanks for your help

**Comment by intraordinaire** [comment]
@tajriba,

As the `mkdir` function tries to create a folder, do you have a `path` specified in the error ?

If yes, please, ensure that you have correctly the rights to write on this folder.
Also, can you provide us a bit more of context ? Screenshots, stacktrace, logs ...

Thanks for your help.

**Comment by intraordinaire** [comment]
I close this issue due to inactivity.

@tajriba, if you have some news, feel free to answer.

Thanks again.
