### ISSUE TITLE
Deprecated: `$usePutenv` argument should be explicitly defined

### ISSUE THREAD

**Issue by SharakPL** [PrestaShopCorp/ps_mbo#509]
Using ps_mbo-v.4.4.0 with PS in debug mode triggers this error:

> Deprecated: The default value of "$usePutenv" argument of "Symfony\Component\Dotenv\Dotenv::__construct" will be changed from "true" to "false" in Symfony 5.0. You should define its value explicitly.

**Comment by intraordinaire** [comment]
Again, thank you for your contribution, really appreciate it !
