### ISSUE TITLE
Errors after installing

### ISSUE THREAD

**Issue by guillemfedez** [PrestaShopCorp/ps_mbo#541]
Hi!

I'm having this issues after installing the module. When I try to reopen the backoffice I have this errors. Hope it helps.

Thank you!

![errorweb1](https://user-images.githubusercontent.com/56740158/235881855-5af7e6f6-d28b-4eaf-bc9f-ad41d3928c67.PNG)
![errorweb2](https://user-images.githubusercontent.com/56740158/235881862-801abec5-b320-431e-86d1-8412dd2d2a3a.PNG)

**Comment by intraordinaire** [comment]
Hello @guillemfedez,

Thanks for your report !

It may be a "cache" problem. Can you try to clear the cache folder of PrestaShop ? Under `PrestaShop-path/var/cache/` ?
Sometimes, when modules are installed, the Symfony cache is not well cleared. So, in the next page load, new services still does not exist in context.

If the problem persists, can you provide us the version of the module & of PS ? If you cloned the repo or download a release, ...

**Comment by guillemfedez** [comment]
Hi @intraordinaire !

Thanks for your quick feedback. I tried to clear the cache but same result. I tried several ways such as download the latest version from website, clone the latest, clone the repo... Same results always. My PS version is 8.0.3

Thank you!

**Comment by intraordinaire** [comment]
@guillemfedez I tried with a fresh PS 8.0.4 this morning and the [last released module 4.4.1](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.4.1) and it worked well.

Can you also give me your PHP version ? 
I'll do some more tests.

**Comment by guillemfedez** [comment]
@intraordinaire mine is 7.3.29, let me know if I can help with anything. Thank you so much!

**Comment by intraordinaire** [comment]
🤔
Tried on two distinct installation with different configuration, and don't have this problem.
Are you trying in local ? Hosted machine ? Docker ? Do you have access to the memory allowed for PHP (`memory_limit` param) ?

**Comment by guillemfedez** [comment]
Looking on the Stack track I see this:
```
TypeError:
Argument 4 passed to PrestaShop\Module\Mbo\Service\View\InstalledModule::__construct() must be of the type string, float given, called in /var/www/vhosts/metroelectronica.com/httpdocs/modules/ps_mbo/src/Service/View/ContextBuilder.php on line 276

  at modules/ps_mbo/src/Service/View/InstalledModule.php:50
  at PrestaShop\Module\Mbo\Service\View\InstalledModule->__construct(0, 'statsgeolocation', 'uninstalled', 1.0, '/adminprestashop/index.php/improve/modules/manage/action/configure/statsgeolocation?_token=q8EodTJLmTd_csjlWfiG_2gjFPFCco7TBxXs8wPNPeQ')
``` 
I tried to search this module but nothing. Hope this gets the clue

**Comment by intraordinaire** [comment]
@guillemfedez oh I see.
Another issue has been opened on this too => #542.

Glad to hear you have found how to fix this.
We'll investigate about this module, and, as said in the other issue, we will fix this `TypeError`.

**Comment by guillemfedez** [comment]
It looks exactly as mine. After renaming ``` statsgeolocation ``` folder it works OK. I checked on ```ps_module``` table and this module is not declared so is the reason why I think it's an older plugin that wasn't erased after upgrading.

Thank you so mucho for your help!

**Comment by intraordinaire** [comment]
Indeed, this module seems to be an old one, not maintained anymore.
Thank you for this exchange, and don't hesitate in case of trouble, we'll be happy to help !
