### ISSUE TITLE
Locked out of admin and shop after issuing update through Prestashop Module Manager

### ISSUE THREAD

**Issue by hoburgt** [PrestaShopCorp/ps_mbo#579]
Update this morning, 27-05-2023, from within Prestashop 1.7.8.7 for a Prestashop module (can't exactly remember which one) did collapse the whole shop. Error 500, no admin, no shop. After looking in the prod.log I see:
**app.ERROR: Exceptie gegooid door module ps_mbo op actie upgrade. Failed to copy the whole content of "/data/sites/web/ramblingrosenl/www/var/cache/prod/sandbox/64717ba5ae2d6/ps_mbo/vendor/prestashop/circuit-breaker/tests/Storage/DoctrineCacheTest.php" to "/data/sites/web/ramblingrosenl/www/modules/ps_mbo/vendor/prestashop/circuit-breaker/tests/Storage/DoctrineCacheTest.php" **
Renaming the directory ps_mbo to ps_mbo.err brought everything back but now I am locked out of any further updates etc. I suppose?!
Can I repair something in this directory to bring it safely back?

Thanks.

**Comment by intraordinaire** [comment]
Hello @hoburgt,

Thanks for your report.
It may be a problem of cache. During modules updates, PS/Symfony cache is cleared, but sometimes, it did not succeed to build correctly on reload.

You can try several options here : 
 - Switch back the ps_mbo.err to ps_mbo : When you did the first change, it "forced" an uninstallation process on the module. You can try to just re-install it.
 - Delete the folder ps_mbo.err and try to manually install the last available version for PS 1.7.8.7 which is the [2.2.0](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v2.2.0)

Hope it will help.

**Comment by hoburgt** [comment]
> Hello @hoburgt,
> 
> Thanks for your report. It may be a problem of cache. During modules updates, PS/Symfony cache is cleared, but sometimes, it did not succeed to build correctly on reload.
> 
> You can try several options here :
> 
> * Switch back the ps_mbo.err to ps_mbo : When you did the first change, it "forced" an uninstallation process on the module. You can try to just re-install it.
> * Delete the folder ps_mbo.err and try to manually install the last available version for PS 1.7.8.7 which is the [2.2.0](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v2.2.0)
> 
> Hope it will help.

Super, thanks for the reply! I did place a backup copy for the ps_mbo directory back after my comment and everything was back as before. I didn't have time yet to look into the solutions you give but as the update offered itself again after my fallback I will try a normal update as before. If that goes wrong again I will probably delete the mbo folder and install the latest version as you describe. Thanks!
