### ISSUE TITLE
AdminPsMboTheme is missing

### ISSUE THREAD

**Issue by snksender** [PrestaShopCorp/ps_mbo#592]
It is showing error in fresh installation.

**Comment by snksender** [comment]
Prestashop version: 9.0.0
Module version: [v4.4.3]
Thanks. I will try clearing cache.

**Comment by intraordinaire** [comment]
@snksender tell me if you have some news.
Did you mean 8.0.0 ? Actually, PrestaShop 9.0 did not exist, so the module can not be compatible yet.

**Comment by snksender** [comment]
![image](https://github.com/PrestaShopCorp/ps_mbo/assets/53807254/3b3a2359-3b5e-4c72-b8d1-23846db2b020)

It is showing 9.0.0 in top-bar

**Comment by intraordinaire** [comment]
@snksender Ok, you are using the `develop` branch of the PrestaShop project.
This branch is still under heavily development, and the release of the 9.0.0 version should not happen before several months. We will update the module before this release, if needed, but in the meantime, I suggest you to get a stable version of PrestaShop, or the last RC of 8.1.

**Comment by intraordinaire** [comment]
Hello @snksender,

Are you still facing this issue with a compliant PS version ?

I close the issue, don't hesitate to re-open an issue if you encounter any trouble.

Thanks.
