### ISSUE TITLE
double include directory for mbo module

### ISSUE THREAD

**Issue by musicpanda** [PrestaShopCorp/ps_mbo#602]
While checking some bug in my PS 8.1 installation I noticed that under Linux there are two include directories under the directory /modules/ps_mbo/views/templates/admin/controllers/module_catalog/. Under Windows they are merged into one.

To be more exact, there are "Include" and "include". So it has something to do with case sensitivity.

See also https://github.com/PrestaShop/PrestaShop/issues/33259

**Comment by intraordinaire** [comment]
Hello @musicpanda,

Thanks for your report !

Is this 8.1 a fresh install or an update ?
Actually, indeed, the folder was name `Includes` in old versions of the module (`2.x`) and is named `includes` now.

2.x versions of module are available for PS 1.7 and 4.x versions, for PS 8.x.

I think this may happen during the update process of module between 2.x <=> 4.x, the folder is not deleted.
We'll log this to fix it in the enxt release.

In the meantime, if you want, you can try to back up the `Includes` folder, everything should work properly, and if it's the case, you can delete it.

Have a great day !

**Comment by musicpanda** [comment]
Hello Intraordinaire,

This was on a fresh 8.1 installation. So there was no updating involved at all.

Regards

**Comment by intraordinaire** [comment]
Hum, ok.
@musicpanda can you tell me what version of the module you are using ?
And where did you download it ?

**Comment by intraordinaire** [comment]
Can you maybe provide us the list of files under each directory ?

**Comment by musicpanda** [comment]
The version is 4.4.3

I assume it has somehow installed with the theme (https://demo.templatemonster.com/demo/301854.html) as its installation is the only thing I have done until now.

**Comment by musicpanda** [comment]
Includes directory (size also shown):
1583 action_button.html.twig
3156 action_menu.html.twig
4835 catalog_card.html.twig
1866 dropdown_bulk.html.twig
3350 menu_top.html.twig
2998 module_actions_buttons.html.twig
2938 sorting.html.twig
4199 tab-module-line.html.twig
3497 tab-modules-list.html.twig

includes directory:
1347 action_button.html.twig
2849 action_menu.html.twig
1129 index.php
5712 modal_addons_connect.html.twig
5455 modal_import.html.twig

**Comment by intraordinaire** [comment]
Indeed, the `Includes` directory here is from the 2.2.x version see [here](https://github.com/PrestaShopCorp/ps_mbo/tree/2.2.x/views/templates/admin/controllers/module_catalog)

In the 4.4.3 you should have only `includes`, see [here](https://github.com/PrestaShopCorp/ps_mbo/tree/4.4.x/views/templates/admin/controllers/module_catalog)

I don't understand how you can have both if it's not from an update. 
If you download a release of PS MBO from github or on the addons marketplace, you should have only one folder.

Can you try to just rename or move the `Includes` folder? Everything should still work as expected.

Thanks

**Comment by musicpanda** [comment]
No news.
Removing the "Includes" directory doesn't seem to have negative effects.

**Comment by intraordinaire** [comment]
Ok, great news in a way.
As we did not reproduce this error, we didn't manage to find this double folder, except if we manually merge modules of different versions, I'll close the issue.

Don't hesitate to re-open it if you have any further element.
