### ISSUE TITLE
New PS8.1.1 Installation, install latest mbo zip

### ISSUE THREAD

**Issue by roja45** [PrestaShopCorp/ps_mbo#620]
New PS8.1.1 Installation, install latest mbo zip

![image](https://github.com/PrestaShopCorp/ps_mbo/assets/19314911/507d50cb-1096-4cc4-bc91-6ee53b9358b7)

**Comment by intraordinaire** [comment]
Hello @roja45 ,

Is that a fresh install, or an update of PS ?

A user is created by the module on installation. Do you have it in db ?
If you try to uninstall/re-install, does the problem persists ?

Anyway, we will look to better handle this exception.
Thanks for your report.

**Comment by maofree** [comment]
Hi
yes it is the same error

to avoid this error it is necessary to remove ps_mbo before to upgrade prestashop from 1.7 to 8.1, then install the ps_mbo v4.5.1

**Comment by roja45** [comment]
New installation.  I just installed 4.4.3 instead.

**Comment by intraordinaire** [comment]
@roja45 , sorry for the delay in the answer, but a better handling of this has been [released 3 weeks ago, with the 4.5.3](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.5.3)
