### ISSUE TITLE
ps_mbo interrupt install on fresh Prestashop Install

### ISSUE THREAD

**Issue by Setlakwe** [PrestaShopCorp/ps_mbo#636]
Step to reproduce : 

- Start a new server
- Unpack prestashop.zip 
- Go through setup .. crashes @ 75% 

![image](https://github.com/PrestaShopCorp/ps_mbo/assets/32545578/dbe8338a-ee8b-448e-85f2-d6b7a8ba2bc8)

Tested on PS: 1.7.8.10 (php7.4)

**Comment by intraordinaire** [comment]
Hello @Setlakwe ,

Thanks a lot for your feedback.

We will release a fix this morning.

**Comment by intraordinaire** [comment]
@Setlakwe Sorry for the delay of my answer, but this should be fixed since Friday.

Anyway, thanks a lot for your report !
And don't hesitate if you find something else.
