### ISSUE TITLE
"PrestaShop Marketplace in your Back Office" module, Marketplace not loading, reloading automatically

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShopCorp/ps_mbo#638]
After installing, "[PrestaShop Marketplace in your Back Office](https://addons.prestashop.com/en/administrative-tools/39574-prestashop-marketplace-in-your-back-office.html#overview_description)" module v4.5.3

"Marketplace" tab is just reloading automatically check the video"

https://www.awesomescreenshot.com/video/20945642?key=19f76c5e52f4a19ad0dd21b01b30f681

Expected behavior
Should load "Marketplace" page properly

Steps to reproduce
Install,
https://addons.prestashop.com/en/administrative-tools/39574-prestashop-marketplace-in-your-back-office.html

and check "Marketplace" tab,

PrestaShop version(s) where the bug happened
8.1.0

PHP version(s) where the bug happened
8.0.34

**Comment by intraordinaire** [comment]
Hello @dheerajwebkul ,

Thanks for your report.
Have you tried to uninstall & install the module again ?

**Comment by dheerajwebkul** [comment]
@intraordinaire  multiple times

**Comment by intraordinaire** [comment]
Hum
I do not find your shop URL in our DB. So the installation does not work well.
Do you have access to your error logs ? Located in `var/logs`

We can not reproduce it with just the same PS version, so we have to find what can produce this.

Maybe, if you open your browser inspector and try to press Escape on your keyboard before a refresh to stop it, we can also have some other JavaScript or network errors there.

**Comment by intraordinaire** [comment]
@dheerajwebkul any news on this subject ? Did you find something in the console or in your logs ?

**Comment by dheerajwebkul** [comment]
Hello @intraordinaire 

no, nothing found in console.

**Comment by intraordinaire** [comment]
@dheerajwebkul , is your `admin_path` validating this regex ? `/^\/[\w\-]+\/$/`
(NB : the admin path is your admin folder name)

**Comment by intraordinaire** [comment]
I close this issue as I don't have any news.

If you still have an issue, I suggest you to try the last version of the module.
If still not working, please tell us, we will help you to investigate and fix if necessary.
