### ISSUE TITLE
Installation of a module in Carriers page

### ISSUE THREAD

**Issue by marionf** [PrestaShopCorp/ps_mbo#66]
Go on Delivery > Carriers
Click on install for module chronopost or mondial relay
You are redirected to improve/modules/catalog instead of controller=AdminPsMboModule 
And the module catalog tab isn't selected

https://drive.google.com/file/d/1TQA3Twxon1BMvfnbdbZJi9WrTr6uMnS9/view?usp=sharing

**Comment by marionf** [comment]
No idea, we can ask to a dev

**Comment by MrBaiame** [comment]
Any update on this ? Or should i close ?

**Comment by marionf** [comment]
It needs investigation to tell if it should be fixed in MBO or in the core 
Can you do it @Alexisvallee ?

**Comment by MrBaiame** [comment]
The URL called is a core url, we probably have to see with the core if the return can be customized
