### ISSUE TITLE
The service "mbo.modules.source_handler.addons_url" has a dependency on a non-existent service "PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler".

### ISSUE THREAD

**Issue by BRIC2DEV** [PrestaShopCorp/ps_mbo#675]
Hi, I'm running into an issue with my prestashop

When I try to get to my back office with debug mode on, I get the following error :

The service "mbo.modules.source_handler.addons_url" has a dependency on a non-existent service "PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler".

When debug mode is turned off I can login and modify things but saving changes sends me to the Internal Server error 500 page.

Anyone knows how to fix the issue ?

**Comment by intraordinaire** [comment]
Hello @BRIC2DEV ,

Can you tell me what are your versions of PS & ps_mbo ?

Thanks

**Comment by intraordinaire** [comment]
The service `PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler` [was added in PrestaShop 8.0.0](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Module/SourceHandler/ZipSourceHandler.php), so you should not have trouble loading it...
Have you tried to empty the cache, by removing everything under `var/logs`

**Comment by BRIC2DEV** [comment]
The version of the module is 4.6.0, and prestashop is 8.0.1

I tried emptying the cache but it didn't work, so I removed the module since it's not so important. It solved it!

Thanks

**Comment by intraordinaire** [comment]
This error was fixed in 4.6.1, you can find it [here](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.6.1) if you want to try it !

Thanks
