### ISSUE TITLE
Almost as bad as ps_edition_basic

### ISSUE THREAD

**Issue by musicpanda** [PrestaShopCorp/ps_mbo#677]
ps_mbo is the source of lots of  problems on the forum.

However, ps_edition_basic is worse. ps_edition_basic requires PHP version 8.1. So its presence in the EDITION BASIC sabotages the compatibility with older PHP versions. 

As you see this only after you have enabled debug mode very few people find this out.

**Comment by intraordinaire** [comment]
Hello,

Thanks for the feedback.
Be sure we are trying our best to handle problems/issues developers or merchants can encounter.

The message about the PHP support version is transmitted.
I close this issue.
