### ISSUE TITLE
Attempted to call function "putenv" from namespace "Symfony\Component\Dotenv".

### ISSUE THREAD

**Issue by matosagencia** [PrestaShopCorp/ps_mbo#716]
"Dotenv->loadEnv('/home/storage/a/b5/c6/ahauss1/public_html/modules/ps_mbo/.env')
in [modules/ps_mbo/bootstrap.php ](https://ahauss.com.br/admin784bfktcq6k3dtfubpf/index.php/_profiler/open?_token=fGvzmhavlivgPrIV72477-PdDimaUaf4OPu1ZCbuEfY?file=modules/ps_mbo/bootstrap.php&line=28#line28)(line 28)
    $rootDir = __DIR__ . '/../../';}require_once $rootDir . '/vendor/autoload.php';(new \Symfony\Component\Dotenv\Dotenv(true))->loadEnv(__DIR__ . '/.env');"
    
    when i try enable this module, the ps_accounts was installed with sucess

**Comment by intraordinaire** [comment]
Hello @matosagencia ,

Can you provide us more details about your issue ?
PS version ? ps_mbo version ?

A screenshot, more logs, or a way to reproduce.

Thanks.
