### ISSUE TITLE
Undefined ps_mbo::$template_dir

### ISSUE THREAD

**Issue by julienmiclo** [PrestaShopCorp/ps_mbo#719]
Hello,
i update my prestashop to 8.1.3 and now when i go to Modules > Marketplace. I have this error : 
`Undefined property: ps_mbo::$template_dir`

Thank you

**Comment by intraordinaire** [comment]
Hello @julienmiclo ,

Thanks for your feedback.
You did the update from PS 1.7.x to 8.1.3 ?
Which version of ps_mbo was and is now installed on your shop ?

Anyway, maybe you can try first to reset the module.
If you still have an issue, you can uninstall and remove the files, and then, upload a zip of the[ last release available on github](https://github.com/PrestaShopCorp/ps_mbo/releases).
If you did an update from an old version, you may have some old unused files remaining in folders, so by making a clean install with a fresh downloaded zip, it can solve the issue.

Hope it'll help !

**Comment by julienmiclo** [comment]
Hello,
I forgot to activate the module.
Sorry

**Comment by intraordinaire** [comment]
Ok then :) 
I close the module.

Don't hesitate to open a new one if you have another issue !
