### ISSUE TITLE
Module image too small + missing changelog 

### ISSUE THREAD

**Issue by SharakPL** [PrestaShopCorp/ps_mbo#726]
### Describe the bug and add attachments

Tested on PS 8.1.2. Detailed information about the module has a very small image and no information about the changes with current update

### Expected behavior

1. Image should fill the container
2. There should be clear information about changes

### Steps to reproduce

1. Modules -> Updates
2. Hit `Read more` on any of the updates

https://github.com/PrestaShop/PrestaShop/assets/5007456/288dffef-9461-4f28-886d-4912c8b0fd2c

**Comment by intraordinaire** [comment]
Hello @SharakPL ,

Thanks for the feedback.

Indeed, it seems that we have an issue with modules without videos, the slider is not loading properly.
And for the changelog, we'll add a fallback text such as "No information provided by the developer" in cases like this.

We'll keep you updated !

Thanks again

**Comment by SharakPL** [comment]
> And for the changelog, we'll add a fallback text such as "No information provided by the developer" in cases like this.

There should be an information about the changes, at least the important ones (fixes + improvements, but no version bumps or dependencies' upgrades). Otherwise no point for this whole block showing last versions.

**Comment by SharakPL** [comment]
And what would be needed to provide such information for mbo? Maybe changelog.xml in each module? Or maybe there is suitable functionality already, just not used properly when making new releases of modules...

**Comment by intraordinaire** [comment]
@SharakPL Actually MBO retrieve data from the [addons marketplace](https://addons.prestashop.com/pl/emaile-powiadomienia/24547-mail-alerts.html). 
I assume natives modules are sent with a github action, automatically on release. So, an update may be needed there to correctly give the changelog. I'm checking with the team.

**Comment by intraordinaire** [comment]
@SharakPL We are testing fixes for the slider & a first improvement for the changelog. This will be released soon (maybe today or monday).
I've looked a bit to correctly add the changelog to the marketplace for natives modules, but, unfortunately, it's not that simple. I logged this improvement in a board on our side.

**Comment by intraordinaire** [comment]
@SharakPL, fixes are released.
As said before, we're also looking to improve the way natives modules are sent to the marketplace.

Again, thanks for your feedback !
