### ISSUE TITLE
Prestashop 8.1.4 The AdminPsMboUninstalledModules controller is unavailable or damaged.

### ISSUE THREAD

**Issue by bsylwek** [PrestaShopCorp/ps_mbo#729]
Hello

Prestashop 8.1.4 The AdminPsMboUninstalledModules controller is unavailable or damaged. 

PrestaShop Marketplace in your Back Office v4.10.1 php v 8.0.23

go to Uninstalled Modules

![uninstalled](https://github.com/PrestaShopCorp/ps_mbo/assets/66308504/a6ee2026-e707-4ceb-83f4-618a6e4d8c4a)

![error](https://github.com/PrestaShopCorp/ps_mbo/assets/66308504/dabddee9-f7ae-4393-897a-1909ae995181)

How to fix it?

**Comment by sowbiba** [comment]
Hello @bsylwek 

Thanks for the issue

Do you have this after after an upgrade of PS ?

**Comment by sowbiba** [comment]
https://github.com/PrestaShopCorp/ps_mbo/assets/7426640/4e90a04a-e796-45ad-a49d-611ef8ed541e

I reproduced it

**Comment by sowbiba** [comment]
Can you please wait until 4.10.2 of ps_mbo is released ?

Hopefully it will arrive very soon. Once it's released, you just have to upgrade to solve your issue

**Comment by bsylwek** [comment]
Yes, of course I can wait for the MBO update. Thank you for the quick reply.

**Comment by sowbiba** [comment]
Hello

ps_mbo v4.10.2 is now available. Please upgrade and tell us if it fixes your issues

Thanks

**Comment by bsylwek** [comment]
Unfortunately there is the same error

**Comment by sowbiba** [comment]
🤔 you did the upgrade and still have the "Uninstalled modules" tab?

If the answer is yes, can you try to disable/re-enable the module or reset it?

Explanation : Still this v4.10.2, everytime the module is enabled, we are checking all the tabs and put them in the right state (delete if not required, add the new ones, hide the technical ones, ...)
We also do that full check when installing or upgrading the module
Resetting a module means uninstall/install

**Comment by sowbiba** [comment]
https://github.com/PrestaShop/PrestaShop/issues/35426

**Comment by bsylwek** [comment]
Previously, after the update, I turned the module on and off and it didn't help. After the reset, the uninstall button disappeared. Is this correct?

![mbo](https://github.com/PrestaShopCorp/ps_mbo/assets/66308504/f1d8ccef-d79f-41a1-a5df-3f0e0c58f971)

**Comment by sowbiba** [comment]
Perfect. If you don't have it anymore, that's fine 😉
