### ISSUE TITLE
ps_mbo/vendor/ramsey/collection/src/AbstractArray.php, line 87 - Error importing orders from Baselinker

### ISSUE THREAD

**Issue by jollymag** [PrestaShopCorp/ps_mbo#735]
Hi,
We are having a issue with our website, we can not import orders from Baselinker to our Prestashop website, www.jollymag.ro
We are reciving this error 
" Error adding the order to the store: [PHP Unknown error #8192] Return type of Ramsey\Collection\AbstractArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (/home/jollymag/public_html/modules/ps_mbo/vendor/ramsey/collection/src/AbstractArray.php, line 87)"

We contacted baselinker and they told us that the ps_mbo module have issue.
Can someone help us with this issue?
Thanks in advance!
Best regards!

**Comment by sowbiba** [comment]
Hello. Thanks for the issue. Can you give us more details please

PrestaShop Version?

Mbo version ?

Php version?

**Comment by jollymag** [comment]
PRESTA: 8.1.2
PHP: 8.1
MBO: v4.6.1  ( We`ve downloaded it direcly from GITHUB ps_mbo_master)

**Comment by jollymag** [comment]
Can you help please?

**Comment by jollymag** [comment]
since we talked we`ve upgrated to v4.10.2 - the problem is still there.

**Comment by sowbiba** [comment]
To help you understand, we faced that issue in December, this was my conclusions


```
We use a ramsey/uuid lib which allows us to generate UUIDs

In MBO, Version 4.2.3 is currently installed, which supports PHP 7.2

https://github.com/ramsey/uuid/blob/4.2.3/composer.json#L12

From version 4.3.0, PHP7 support is removed

https://github.com/ramsey/uuid/blob/4.3.0/composer.json#L12

So we are stuck on 4.2.3, as MBO requires PHP>=7.2.5

Ramsey/uuid require ramsey/collection (1.0 + and < 2.0)

It is in this lib that the signature of the offsetGet method is not respected as it should be

We are currently using version 1.1.4 of this lib

The error reported is corrected in version 1.2.0 but we cannot switch to this version because its support is PHP7.3+

[https://github.com/ramsey/collection/blob/1.2.0/composer.json#L22
]

So we are stuck

 

 

As this error is not blocking and in prod mode it does not appear, WONT FIX

We will upgrade to the correct versions if our PHP support changes
```

**Comment by sowbiba** [comment]
> since we talked we`ve upgrated to v4.10.2 - the problem is still there.

Thanks for the answer 👌🏾 , we will release a 4.10 patch very soon 🤞🏾

**Comment by jollymag** [comment]
ok, can you please let us know when the release for the new patch will be?
Thanks a lot!

**Comment by sowbiba** [comment]
Hopefully before tomorrow evening 🤞🏾 Or it'll we next week

Depending on reviews and QA

**Comment by sowbiba** [comment]
Github release done

https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.10.3

**Comment by jollymag** [comment]
Hi,
We`ve istaled the new version.
But the problem is not resolved!
"Error adding the order to the store: [PHP Unknown error #8192] Return type of Ramsey\Collection\AbstractArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (/home/jollymag/public_html/modules/ps_accounts/vendor/ramsey/collection/src/AbstractArray.php, line 87)"

**Comment by jollymag** [comment]
even with the version v4.10.3  - is the same problem :(
Any other ideeas?

**Comment by jollymag** [comment]
> Github release done
> 
> https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.10.3

Please help!
