### ISSUE TITLE
ps_mbo/vendor/ramsey/collection/src/AbstractArray.php, line 87 - Error importing orders from Baselinker

### ISSUE THREAD

**Issue by jollymag** [PrestaShopCorp/ps_mbo#737]
Hi,
We are having a issue with our website, we can not import orders from Baselinker to our Prestashop website, [www.jollymag.ro](http://www.jollymag.ro/)
We are reciving this error
" Error adding the order to the store: [PHP Unknown error #8192] Return type of Ramsey\Collection\AbstractArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (/home/jollymag/public_html/modules/ps_mbo/vendor/ramsey/collection/src/AbstractArray.php, line 87)"

We contacted baselinker and they told us that the ps_mbo module have issue.
Can someone help us with this issue?
Thanks in advance!
Best regards!

PRESTA: 8.1.2
PHP: 8.1
MBO:  v4.10.3 
Problem is still not resolved!
Please help!
@sowbiba

**Comment by jollymag** [comment]
ITs 100% MBO 4.10.3
Error is the same:
Error adding the order to the store: [PHP Unknown error #8192] Return type of Ramsey\Collection\AbstractArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (/home/jollymag/public_html/modules/ps_accounts/vendor/ramsey/collection/src/AbstractArray.php, line 87)

**Comment by sowbiba** [comment]
... (/home/jollymag/public_html/modules/**ps_accounts**/vendor/ramsey/collection/src/AbstractArray.php, line 87)

**Comment by jollymag** [comment]
So we resolved 1 problem and hit another one with PS_ACCOUNT. omg :(
Thanks!
Will open ticket there.
Thanks for the help!

**Comment by sowbiba** [comment]
Hello. I send them the issue.
They are aware of it and they will get rid of the library in their next major version

But ... it's announced on ... April 😶‍🌫️ 

If you have access to the source code of ps_accounts, please try to apply the same fix as we did on ps_mbo

**Comment by intraordinaire** [comment]
I close the issue as it no longer belongs to ps_mbo.
Hope you've found a way to fix it.
