### ISSUE TITLE
Unexpected alert message on recommended-modules.tpl?

### ISSUE THREAD

**Issue by albert28** [PrestaShopCorp/ps_mbo#745]
Hi!

In version 3.1.0 there's this alert message in recommended-modules.tpl.

`} else {
    alert('wooow')
  }`

**Comment by intraordinaire** [comment]
Hello @albert28 

Indeed, code review has been done a bit too quick on this one 🙈 
Will release a new version this week.

Thanks for your feedback !

**Comment by intraordinaire** [comment]
The release [v.3.1.1](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v3.1.1) has been done

Again, thanks for your feedback
