### ISSUE TITLE
prestashop gives me this error after installing the theme on the home page

### ISSUE THREAD

**Issue by Telephonehelp** [PrestaShopCorp/ps_mbo#756]
version prestashop 8.1.4 
error 
The AdminPsEditionBasicHomepageController controller is missing or invalid.

**Comment by Telephonehelp** [comment]
Yes, some problems were cleaned up between the module and the new prsta shop, the php version was also changed, bringing it to 8.1

**Comment by intraordinaire** [comment]
@Telephonehelp , so you still have this error ? 
If yes, can you provide if possible a stacktrace, screenshots, tell us which theme you are talking about...

Thanks

**Comment by intraordinaire** [comment]
As we don't have any news, I close the issue.

Feel free to reopen it if needed, or open another if you find something else.

Thanks !
