### ISSUE TITLE
Cannot install or update module from Marketplace

### ISSUE THREAD

**Issue by tone87** [PrestaShopCorp/ps_mbo#757]
I cannot install or update any module from Marketplace ...
in updating module from marketplace say an error like " wrong url shop"

I have a multishop active
Prestashop 8.1.6
PHP 8.1.28
MySQL: 10.11.8-MariaDB-log

https://github.com/PrestaShopCorp/ps_mbo/assets/8173557/d2387896-5875-4dca-ac0c-9eaf8500cab4

**Comment by jinpresta** [comment]
Hello @tone87,

Thank you for your feedback.

Could you please send us your shops' urls ? 

Thanks

**Comment by tone87** [comment]
> Hello @tone87,
> 
> Thank you for your feedback.
> 
> Could you please send us your shops' urls ?
> 
> Thanks

Yes,
Main site is fershop.it 
But i have multistore with:
Fershop.fr 
Fershop.de 
Fershop.eu
Fershop.es

I installed prestashop assistance module

**Comment by sullivan-monteiro** [comment]
Hello @tone87,
We have checked your store in our database and the stored's url with PrestaShop version 8.1.6 is `de.fershop.it`. We also have an older version with just `fershop.it` but it's still in PrestaShop version 8.1.2.
Can you check the url in your backoffice is correct ? ( Shop parameters -> Traffic & SEO -> Set shop URL)

![Capture d’écran 2024-05-20 à 14 42 25](https://github.com/PrestaShopCorp/ps_mbo/assets/37255886/f67c0c02-8901-41e5-82a1-bdd4d99ecde1)

Thanks

**Comment by tone87** [comment]
The problem is at multistore active ...
as you can see by my screenshot it select automatically the first url from list ... but is not the real main domain .. the rela main domain is "fershop.it" -> https://fershop.it
i searched on database table .. but there is no way to ordering .. i don't know the system order the store urls
![image](https://github.com/PrestaShopCorp/ps_mbo/assets/8173557/dafc6f76-e35b-439a-8bc5-301084fd21a8)

**Comment by intraordinaire** [comment]
@tone87 
We just released [v4.11.3](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.11.3), can you test with it ?

**Comment by tone87** [comment]
Hi ! on updating module yes, it works !.
On install it going on error . i think is a problem on CORS i attach screenshot console
![image](https://github.com/PrestaShopCorp/ps_mbo/assets/8173557/7bf243a2-3bd5-4913-80ca-77dfb591b5f2)

**Comment by tone87** [comment]
i tried to reset module but nothing change for install .. i attach the video with console opened

https://github.com/PrestaShopCorp/ps_mbo/assets/8173557/b8aa28fb-0aa1-40f7-bba6-3f228add2908

**Comment by intraordinaire** [comment]
Hello @tone87 ,
Thanks a lot for your time and data you give to us.

We are investigating on what happened on your shop (seems to work fine on all our test shops).
Is your shop under some firewall or network protection ? Cloudflare or something like that ?

It seems like we receive a 403 from our API call when trying to launch install.

We are searching for a solution.

**Comment by intraordinaire** [comment]
@tone87 we have found something and are testing a workaround for this case.
We will update our API / Frontend, so an update of the module will not be necessary.

We plan to release it ASAP, so tomorrow or beginning of the next week.

We'll keep you updated in order to validate everything's fine after that.

Thanks a lot for your help & patience 🙏

**Comment by intraordinaire** [comment]
Hi @tone87 ,

We released an update on our APP, can you test again ? 🙏

**Comment by intraordinaire** [comment]
Ok, this action seems to be outdated now.
Can you try to empty Chrome cache ?

**Comment by tone87** [comment]
yes, i'm sorry , now it works ! super thanks !

**Comment by intraordinaire** [comment]
Wonderful !
Thanks to you !
