### ISSUE TITLE
When I click on Configure, I'm not in the right link 

### ISSUE THREAD

**Issue by AureRita** [PrestaShopCorp/ps_mbo#762]
### Descritpion

When I want to click on configure to setup my module, I have the name of my shop with it double link as you can see : 

[recording(216).webm](https://github.com/PrestaShopCorp/ps_mbo/assets/100699445/d9fa2f0e-3b85-49be-a8c2-d266355b7b3e)

### Expected Behavior

I wish I could go on the configuration of the module by the marketplace 

### Steps to reproduce
1. Install a fresh version of prestashop 1.7.8.11 in local
2. Go into the BO 
3. Clic on Module > Marketplace
4. Writte "Mail" in the search field
5. Install "Mail alert" 
6. Clic on Configure :x: 

### Prestashop version 
1.7.8.11 

### PHP Version
7.4 

### MBO Version 
3.1.3

**Comment by LouiseBonnard** [comment]
Hi @AureRita, thanks for noticing this bug - and the clear explanations, it's highly appreciated! Can you please turn it into a [JIRA ticket for the MME team](https://forge.prestashop.com/projects/MME/summary) so we can fix it in the next few weeks?

**Comment by NicolasJOUGNEAU** [comment]
Thanks @AureRita, I have created the ticket in our board Jira : https://forge.prestashop.com/browse/MME-270

**Comment by NicolasJOUGNEAU** [comment]
Hi @AureRita, the ticket have been released. If you want check on your side.

**Comment by intraordinaire** [comment]
Mark as closed.
