### ISSUE TITLE
Using php-function "array_merge" as a modifier is deprecated

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShopCorp/ps_mbo#763]
Cf. https://github.com/PrestaShop/PrestaShop/issues/36273#issuecomment-2167830924

Issue located there : https://github.com/PrestaShopCorp/ps_mbo/blob/bc9c71e6fd62d648ed3faede65f308d9c334c883/views/templates/hook/dashboard-zone-one.tpl#L43

**Comment by matks** [comment]
Here is the PR where Smarty introduced this deprecation https://github.com/smarty-php/smarty/pull/814

**Comment by lim3ra** [comment]
Same problem on 8.1.7

**Comment by intraordinaire** [comment]
Hello,

Thanks a lot for the feedback, we will try to patch it for the next release.

Keep you updated.

**Comment by intraordinaire** [comment]
We will release the version today
