### ISSUE TITLE
Bug regarding backoffice marketplace and prestashop addons marketplace

### ISSUE THREAD

**Issue by Kullcord** [PrestaShopCorp/ps_mbo#770]
I am trying to install some addons for my Prestashop website. When I go to modules>marketplace, I get an error saying that This page can't be loaded, please reload" screen that only asks me to reload the page. Once I reloaded, I am told that the "prestashop marketplace for backoffice" is not working and that I need to uninstall it from module>module manager, and then install the new version from the Prestashop Addons Marketplace. I did this, so I uninstalled the "Prestashop marketplace for backoffice", and I went to the Prestashop Addons Marketplace to install the module. When I arrive here, I am told that I need to sign in to install an addon. When I press the sign in button, I am taken to the "create an account" page, instead of the log in page, and I am unnable to log in, and install the module. So right now, whatever module I need for my website, I am unable to get it because of these two bugs. I am going to attach some images regarding the backoffice problem I have, but the text is in Romanian.
![image](https://github.com/user-attachments/assets/bbf26745-c6f3-47a2-8ba6-e7a1b63e0aab)
![image](https://github.com/user-attachments/assets/738ffc44-d91b-4534-9e24-6825fc104164)
![image](https://github.com/user-attachments/assets/f6a38a2e-fae5-47cc-82b2-318b28c1e1cd)
![image](https://github.com/user-attachments/assets/a5e6824b-5132-40ce-bcde-88af1efbf359)

Expected behavior
I expect to be able to, first of all, install the prestashop marketplace for your backoffice module so I can get any addon I want, and in order to do this, I expect to be able to be redirected to the log in page when I press on the log in button on prestashop addons marketplace.

Steps to reproduce
Go to module>marketplace
Press reload
Go to Prestashop Addons Marketplace
Press on log in button
PrestaShop version(s) where the bug happened
8.1.2

PHP version(s) where the bug happened
8.1.25

If your bug is related to a module, specify its name and its version
Prestashop Marketplace for your Backoffice - v4.11.4

Your company or customer's name goes here (if applicable).
Future Energy Group SRL

I was asked to duplicate the bug report and move it to ps_mbo, so here am I.

**Comment by intraordinaire** [comment]
@Kullcord ,

Thanks for your feedback.

When you try to sign in on the website, the website is asking you to finalize the creation of your account.
You should already have an account, but never have downloaded or bought a module with it on the marketplace, so we need you to approve the terms & conditions.

If you validate this step, you should be able to log in, and then, to download the module.

Please, tell me if reinstalling a clean version of the module help you.
