### ISSUE TITLE
Can't install modules from marketplace

### ISSUE THREAD

**Issue by Exoseed** [PrestaShopCorp/ps_mbo#778]
Hello,

On a fresh install of Prestashop 8.1.7, I manually installed ps_mbo and can access the marketplace but whenever I click on "Install" on any module, I get an error message saying "An error occured [...]. Failed to fetch" and nothing happens. I can't seem to figure why.

Thanks in advance for your help!

**Comment by intraordinaire** [comment]
Hello @Exoseed ,

Thanks a lot for your feedback.

Can you give us a bit more details please?
Is your shop a local/dev one or one accessible online ?
What is your PHP version ?
Can you screenshot the error, or give us the entire message (through the console) ?

**Comment by Exoseed** [comment]
Hey,

The shop is online on a shared hosting. Php version is 8.1.30.
Here is a screenshot of the error.
And the console prints this:
`"Fetch API cannot load http://ambiancerideaux.com/backend/index.php/improve/modules/manage/action/install/mailchimppro?_token=HB0PlDzlY9iDJZX2juIGgBQQ5fuKayUjOb1K1wUeEmI&module_id=26957. Request mode is "same-origin" but the URL's origin is not same as the request origin https://ambiancerideaux.com."`

If I understand this correctly, this seems like an SSL error but I don't understand why the installation calls a http route.

Weirdest thing is, I had this error in Chrome and Edge, but I just tested on Firefox and it works fine for some reason.

![Capture](https://github.com/user-attachments/assets/040334b5-2f3a-4418-8b18-fee2a202c3a0)

**Comment by intraordinaire** [comment]
Hum strange indeed as Firefox usually has more secure rules.

Can you check in "Paramètres de la boutique > Paramètres généraux" and tell me if everything is well configured about SSL ?
<img width="1561" alt="image" src="https://github.com/user-attachments/assets/9e1a9094-31f0-4eb9-9452-a76e1fdfe618">

And/or, if you have access to the DB, what is the result of this request 
`SELECT name, value FROM `ps_configuration` WHERE `name` LIKE '%SSL%'; `

**Comment by Exoseed** [comment]
Ok so the second option was not checked for some reason, it works now. Thanks for your help, I can close this issue. My bad!
