### ISSUE TITLE
notice in module 

### ISSUE THREAD

**Issue by Payalba** [PrestaShopCorp/ps_mbo#90]
Hi,

I had a notice in the modue ps_mpo :f ile ps_mpo.php line 320

`if (ADMIN_LEGACY_CONTEXT === true) {`

I replaced this line by 

`if ($this->isAdminLegacyContext()) {`

I don't know if it is the good solution.

Regards,

PYT

**Comment by Matt75** [comment]
@Payalba Thanks for opening an Issue 🥳

Yes this is a good way to fix the notice 👍

This will be fixed in next version of this module soon. 🚧
